version: '3'

services:
  php-app:
    image: php:7-fpm-alpine
    container_name: php-fpm-test-app

    volumes:
      - ./volumes/html:/code

    networks:
      - default

  web:
    image: nginx
    container_name: php-fpm-test-nginx

    links:
      - php-app

    volumes:
      - ./volumes/config/site.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/html:/code
      - ./volumes/log/nginx:/var/log/nginx/

    environment:
      - VIRTUAL_HOST=php-fpm-test.localhost
    networks:
      - default
      - nginx-proxy-network

networks:
  default:
  nginx-proxy-network:
    external: true
