version: '3'

services:
  php-app:
    image: php:7-fpm-alpine
    container_name: php-fpm-test-app

    volumes:
      - ./html:/code

    logging:
      driver:

  web:
    image: nginx
    container_name: php-fpm-test-nginx

    links:
      - php-app

    volumes:
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
      - ./html:/code
      - ./volumes/log/nginx:/var/log/nginx/

    environment:
      - VIRTUAL_HOST=php-fpm-test.localhost

networks:
  default:
    external:
      name: nginx-proxy-net