version: '3'

services:
  php-app:
    image: php:7-fpm-alpine
    container_name: php-fpm-test-app

    volumes:
      - ./volumes/html:/code

    networks:
      - default

  web:
    image: nginx:alpine
    container_name: php-fpm-test-nginx

    links:
      - php-app

    volumes:
      - ./volumes/config/site.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/html:/code
      - ./volumes/log/nginx:/var/log/nginx/

    labels:
      - "traefik.frontend.rule=Host:php-fpm-test.localhost"
      - "traefik.backend=php-app"
      - "traefik.docker.network=proxy-network"

    networks:
      - default
      - proxy-network

networks:
  default:
  proxy-network:
    external: true
