version: '3'

services:
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    restart: unless-stopped

    volumes:
      - ./data/:/bitnami/dokuwiki/data

    environment:
      - DOKUWIKI_USERNAME=admin
      - DOKUWIKI_PASSWORD=admin

    labels:
      - traefik.frontend.rule=Host:wiki.localhost
      - traefik.port=80
      - traefik.docker.network=proxy-network

networks:
  default:
    external:
      name: proxy-network