version: '3'

services:

  # user: admin
  # pass: asdfghjk
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/data:/data

    labels:
      - traefik.frontend.rule=Host:portainer.localhost
      - traefik.port=9000
      - traefik.docker.network=proxy-network

networks:
  default:
    external:
      name: proxy-network
